### ISSUE TITLE
Help needed.

### ISSUE THREAD

**Issue by NiHuShu** [dhustkoder/avrshock2#3]
Hi. Could you make an example of using a button? Something like if up pressed do something. That would help me understand how this works

**Comment by dhustkoder** [comment]
Hi.
The "avrshock2_button_t" values are defined here: https://github.com/dhustkoder/avrshock2/blob/master/src/avrshock2.h#L12

In this example it lists the state of the buttons: 
https://github.com/dhustkoder/avrshock2/blob/master/src/example.c#L78

You could do something like this using the "buttons" variable:
```c
        if (buttons&AVRSHOCK2_BUTTON_CROSS) {
                // do stuff if the X (cross) button is pressed
        } else {
                // do stuff if the X (cross) button is unpressed
        }
```

Let me know if you need help

**Comment by NiHuShu** [comment]
Thank you :D This is gonna really help me

**Comment by NiHuShu** [comment]
Maybe I need a little more help. How to define ports to make it work?

**Comment by dhustkoder** [comment]
@NiHuShu You can define ports in the makefile: https://github.com/dhustkoder/avrshock2/blob/master/makefile#L17

Use your micrcontroller's  datasheet  to find the ports names

**Comment by NiHuShu** [comment]
I've tried but I think that I don't have enough knowledge to make this project my self. Could you help me to merge your project with https://github.com/bootsector/XBOXPadMicro so that I could make PS2 controller to XBOX adapter?

**Comment by dhustkoder** [comment]
@NiHuShu sorry I have been working and I coulnd't reply to your issue. I'll close this but if you're still interested in this project we can talk about it.
